apiVersion: v1
kind: Pod
metadata:
  name: vae1
spec:
  restartPolicy: OnFailure
  containers:
  - name: vae1
    image: zsl3203/vae
    command: ["./run.sh"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "3"